// Code generated by protoc-gen-gogo.
// source: protoStat.proto
// DO NOT EDIT!

/*
Package protoStat is a generated protocol buffer package.

It is generated from these files:
	protoStat.proto

It has these top-level messages:
	ProtoStat
	ProtoStats
*/
package protoStat

import proto "code.google.com/p/gogoprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ProtoStat struct {
	Key              *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	IndexKey         *float64 `protobuf:"fixed64,3,opt,name=indexKey" json:"indexKey,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoStat) Reset()         { *m = ProtoStat{} }
func (m *ProtoStat) String() string { return proto.CompactTextString(m) }
func (*ProtoStat) ProtoMessage()    {}

func (m *ProtoStat) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ProtoStat) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *ProtoStat) GetIndexKey() float64 {
	if m != nil && m.IndexKey != nil {
		return *m.IndexKey
	}
	return 0
}

type ProtoStats struct {
	Stats            []*ProtoStat `protobuf:"bytes,1,rep,name=stats" json:"stats,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ProtoStats) Reset()         { *m = ProtoStats{} }
func (m *ProtoStats) String() string { return proto.CompactTextString(m) }
func (*ProtoStats) ProtoMessage()    {}

func (m *ProtoStats) GetStats() []*ProtoStat {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
}
