// Code generated by protoc-gen-go.
// source: stat.proto
// DO NOT EDIT!

/*
Package zmqOutput is a generated protocol buffer package.

It is generated from these files:
	stat.proto

It has these top-level messages:
	ProtoStat
*/
package zmqOutput

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ProtoStat struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *uint64 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoStat) Reset()         { *m = ProtoStat{} }
func (m *ProtoStat) String() string { return proto.CompactTextString(m) }
func (*ProtoStat) ProtoMessage()    {}

func (m *ProtoStat) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ProtoStat) GetValue() uint64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func init() {
}
